#!/usr/bin/env python3.10
from coordinates import get_gps_coordinates
from exceptions import ApiServiceError, CantGetCoordinates, StorageError
from config import formatter, weather_service, weather_printer
from config import storage, save_weather


def main() -> None:
    try:
        coordinates = get_gps_coordinates()
    except CantGetCoordinates:
        print("Не удалось получить GPS координаты.")
        exit(1)
    try:
        weather = weather_service.get_weather(coordinates)
    except ApiServiceError:
        print(f"Не удалось получить погоду по координатам {coordinates}")
        exit(1)
    formatted_weather = formatter.format_weather(weather)
    weather_printer.display_weather(formatted_weather)

    try:
        # base err handling for storage
        save_weather(weather, storage)
    except StorageError:
        print("Storage file error.")
        exit(1)


if __name__ == "__main__":
    main()
